### ISSUE TITLE
Learning more on the way to envoy configs

### ISSUE THREAD

**Issue by pcn** [stripe/skycfg#40] opened 2019-01-28 02:48 UTC
I've run into another oddity in trying to get skycfg to produce envoy configs. In this case it appears there is some issue with producing UInt32Value messages. The situation is here:

https://gist.github.com/pcn/712a6d4e1c24bd52f82b360cd8a7cd72

The error message is this:
```
panic: TypeError: value <google.protobuf.UInt32Value value:20 > (type `google.protobuf.UInt32Value') can't be assigned to type `google.protobuf.UInt32Value'.
```

I've tried to take a stab at adding the support for this myself but I'm not 
```
diff --git a/internal/go/skycfg/proto_message.go b/internal/go/skycfg/proto_message.go
index b6a65f6..18f3dd1 100644
--- a/internal/go/skycfg/proto_message.go
+++ b/internal/go/skycfg/proto_message.go
@@ -29,6 +29,7 @@ import (
        "github.com/golang/protobuf/proto"
        "github.com/golang/protobuf/ptypes"
        dpb "github.com/golang/protobuf/ptypes/duration"
+       pbwrap "github.com/golang/protobuf/ptypes/wrappers"
        "go.starlark.net/starlark"
        "go.starlark.net/syntax"
 )
@@ -372,6 +373,22 @@ func valueFromStarlark(t reflect.Type, sky starlark.Value) (reflect.Value, error
 
                        return reflect.ValueOf(d), nil
                }
+               fmt.Println(sky.msg)
+               msg_uint32_val, ok := sky.msg.(*pbwrap.UInt32Value)
+               fmt.Printf("OK is %s\n", ok)
+               fmt.Printf("t is %s\n", t)
+               //              fmt.Printf("But *types.UInt32Value doesn't seem to exist? %s", reflect.TypeOf(types.UInt32Value))
+               fmt.Printf("reflect.TypeOf(pbwrap.UInt32Value{Value: 0}) is %s\n", reflect.TypeOf(pbwrap.UInt32Value{Value: 0}))
+               fmt.Printf("reflect.TypeOf(sky.msg) is %s\n", reflect.TypeOf(sky.msg))
+               if ok && fmt.Sprintf("%s", t) == "*types.UInt32Value" {
+                       // if ok && t == types.UInt32Value {
+                       fmt.Printf("I'm here\n")
+
+                       return reflect.ValueOf(msg_uint32_val), nil
+               }
+
+               fmt.Printf("I'm there\n")
+
        case *protoRepeated:
                return valueFromStarlark(t, sky.list)
        case *starlark.List:
```
But that is not working. I'm not sure where the `*types.UInt32Value` comes from, so I'm curious about how to properly use the type system to match that type instead of string-ifying the `reflect.TypeOf` (which is reporting a type.UInt32Value, and I'm not sure what the `type` namespace is in this case), and also how to properly return the `reflect.ValueOf` of the value.

Thanks!

**Comment by jmillikin** [comment] 2019-01-28 03:17
This is caused by the Envoy repository checking in code built with GoGo, and the GoGo structs for `Uint32Value` et al being incompatible with the standard Protobuf library's versions. The fix would be a bit tricky because we don't want Skycfg to depend on GoGo (see details below).

As a workaround, try:

```python
thresh = proto.from_json(v2_cluster.CircuitBreakers.Thresholds, '{"max_connections": 20}')
```

Parsing JSON is expected to work, but might hit some internal assertions because we have very little use of GoGo plus Skycfg internally to test with.

---

The GoGo generated code looks like:

```go
import types "github.com/gogo/protobuf/types"

type CircuitBreakers_Thresholds struct {
	MaxConnections *types.UInt32Value
        // ...
}
```

The required conversion is from [`"github.com/golang/protobuf/ptypes/wrappers".UInt32Value`](https://godoc.org/github.com/golang/protobuf/ptypes/wrappers#UInt32Value) built by Skycfg, to [`"github.com/gogo/protobuf/types".UInt32Value`](https://godoc.org/github.com/gogo/protobuf/types#UInt32Value) expected by GoGo.

There might be something we can do to auto-convert, either transiting `from.Marshal() -> to.Unmarshal()` via reflection or enumerating the "well known" types with type assertions. I'm not eager to do this because the code would be rough, but I can walk you through the details and review a PR if you have time.

Rough sketch: you'd want a map from fully-qualified output type name to conversion function, and use that map to convert from the Protobuf input to the GoGo output. The conversion would perform the type check, and the result could be set on the parent struct with reflection.

**Comment by pcn** [comment] 2019-01-28 16:22
I'm understanding this issue a bit better now. I'll see what I can do. Thanks again for taking the time to explain the situation, the discussion here has been very helpful.

**Comment by jmillikin-stripe** [comment] 2019-01-28 20:16
Above PR has merged. @pcn, can you try out the `gogocompat` package in your code and see if it helps?

**Closed** 2019-01-29 14:25 UTC
