### ISSUE TITLE
Another envoy-related question - duration bottoming out as "time".Duration

### ISSUE THREAD

**Issue by pcn** [stripe/skycfg#32] opened 2019-01-08 14:37 UTC
Trying to assign to an `envoy.api.v2.Cluster.connect_timeout` seems to end up tripping over this definition:

https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/cds.proto#L114-L118

which seems to translate to https://github.com/envoyproxy/go-control-plane/blob/master/envoy/api/v2/cds.pb.go#L261

I guess this is another issue with gogo, but I'm not much of a gopher, so hopefully this helps.

I'm using the same main.go as in my prior issues, here is the sky file:

```python
pb = proto.package("google.protobuf")
v2 = proto.package("envoy.api.v2")

def duration():
    return v2.Cluster(
        lb_policy=v2.Cluster.LbPolicy.ROUND_ROBIN,  # RR is the default, but let's be explicit
        type=v2.Cluster.DiscoveryType.STRICT_DNS,
        connect_timeout=pb.Duration(seconds=0, nanos=500000000),  #0.5 seconds
        name="no_duration")
     
duration()  
```

The output is this:

```
./envoy-proto no_duration.sky
panic: TypeError: value <google.protobuf.Duration nanos:500000000 > (type `google.protobuf.Duration') can't be assigned to type `"time".Duration'.

goroutine 1 [running]:
main.main()
	/home/spacey/go/src/github.com/pcn/envoy-proto/main.go:69 +0x6f3
```

**Comment by dilyevsky** [comment] 2019-01-08 16:44
`connect_timeout` has `(gogoproto.stdduration) = true` option so it gets a `time.Duration` binding:

https://github.com/envoyproxy/go-control-plane/blob/a09b615551f6665e7f8321bbb899670b384224c0/envoy/api/v2/cds.pb.go#L261

Since `time.Duration` is just an alias to `int64` containing nanosecond count, can you try just assigning it to `500000000`?

If it works, might still be a good idea to leave this open as FR to implement time conversion helper - a la `connect_timeout = time.duration('0.5s')`.

**Comment by pcn** [comment] 2019-01-08 17:16
What type would you use to specify the value? So far these haven't worked:

Just using an integer:
`        connect_timeout=500000000,  #0.5 seconds`
```
./envoy-proto envoy.sky
panic: TypeError: value 500000000 (type `int') can't be assigned to type `"time".Duration'.

goroutine 1 [running]:
main.main()
	/home/spacey/go/src/github.com/pcn/envoy-proto/main.go:74 +0x6e3
```

Using a protobuf?
`        connect_timeout=pb.Int64Value(value=500000000),  #0.5 seconds`
results in:
```
./envoy-proto envoy.sky
panic: TypeError: value <google.protobuf.Int64Value value:500000000 > (type `google.protobuf.Int64Value') can't be assigned to type `"time".Duration'.

goroutine 1 [running]:
main.main()
	/home/spacey/go/src/github.com/pcn/envoy-proto/main.go:74 +0x6e3
```

I'm not sure if this is really relevant, but according to the skylark/starlark [language spec](https://docs.bazel.build/versions/master/skylark/language.html), integers are 32-bit, but the [starlark-go](https://github.com/google/starlark-go/blob/master/starlark/int.go) source seems to indicate that it'd be producing an int64. So I'm not sure if there's an escape hatch for me here?

**Comment by dilyevsky** [comment] 2019-01-08 17:18
Whelp, gotta make that `time.duration` helper then. I'll send a change today/tomorrow.

> I'm not sure if this is really relevant, but according to the skylark/starlark language spec, integers are 32-bit, but the starlark-go source seems to indicate that it'd be producing an int64. So I'm not sure if there's an escape hatch for me here?

Yeah, there are some minor differences between Go and Java implementations...

**Closed** 2019-01-10 00:03 UTC

**Comment by pcn** [comment] 2019-01-11 15:42
@dilyevsky is there something I need to know to enable this? I'm using `stripe/master` but I'm getting the same error as before after modifying the custom registry per #35.

**Comment by pcn** [comment] 2019-01-14 16:07
@dilyevsky I'm not sure if you saw my question above, but this doesn't seem to be working for me just yet. Does my reproducer above work for you?

**Comment by dilyevsky** [comment] 2019-01-14 16:17
Hm it did work in my quick test. Lemme double check and publish a branch

**Comment by pcn** [comment] 2019-01-15 15:41
@dilyevsky I must be doing something wrong. Here's a transcript of what's going on: https://gist.github.com/pcn/61d2511cfb2f8fb8b2b81f2a77f80d3c

**Comment by dilyevsky** [comment] 2019-01-15 16:36
Ah, sorry I thought it was a different issue. The error looks like you didn't pick up the latest skycfg dependency version. Since we didn't tag any releases yet, I think you need to `go get -u <pkg>` or `go get -u=patch <pkg>` to pick it up (nuclear option is to delete your `go.mod` so it can be rebuilt from scratch). It definitely works in the master and I added a test for that. Let me know if this doesn't work.

**Comment by pcn** [comment] 2019-01-23 12:03
@dilyevsky here's what I've just tried:

```
|S|spacey@masonjar:~/go/src/github.com/pcn/reproducer$ time go get -u github.com/stripe/skycfg

real	0m6.724s
user	0m0.651s
sys	0m0.136s

|S|spacey@masonjar:~/go/src/github.com/pcn/reproducer$ (cd ../../stripe/skycfg; git status; git log | head)
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
commit fd6aafa80b336fb3a4a5e35c8510d7bb375fa862
Author: dilyevsky <ilyevsky@gmail.com>
Date:   Wed Jan 9 16:03:17 2019 -0800

    Support gogoproto.stdduration option. (#35)
    
    Support `gogoproto.stdduration` gogo proto option that generates plain `time.Duration` as proto field via implicit conversion from gogo's `google.protobuf.Duration` proto.
    
    Example usage:
    \```python
|S|spacey@masonjar:~/go/src/github.com/pcn/reproducer$ time go build

real	0m1.726s
user	0m1.833s
sys	0m0.270s
|S|spacey@masonjar:~/go/src/github.com/pcn/reproducer$ ./reproducer time_reproducer.sky 
panic: TypeError: value <google.protobuf.Duration nanos:500000000 > (type `google.protobuf.Duration') can't be assigned to type `"time".Duration'.

goroutine 1 [running]:
main.main()
	/home/spacey/go/src/github.com/pcn/reproducer/main.go:62 +0x65b
|S|spacey@masonjar:~/go/src/github.com/pcn/reproducer$ ls -laF
total 23364
drwxrwxr-x 2 spacey spacey     4096 Jan 23 06:55 ./
drwxr-xr-x 5 spacey spacey     4096 Jan  4 06:58 ../
-rw-rw-r-- 1 spacey spacey     2027 Jan 15 10:37 main.go
-rwxr-xr-x 1 spacey spacey 23902412 Jan 23 06:55 reproducer*
-rw-rw-r-- 1 spacey spacey      952 Jan  4 07:04 reproducer.sky
-rw-rw-r-- 1 spacey spacey      383 Jan 15 08:53 time_reproducer.sky
```
There's no go.mod, everything's up to date, so I must be missing doing something different from what you're doing on your end, I guess. Any other ideas about what that might be?

**Comment by pcn** [comment] 2019-01-25 00:32
@dilyevsky I got a colleague to build a comparison, and unfortunately it failed in the same way it failed for me. Is there a way I can get you better info to resolve this?

Thanks!

**Comment by dilyevsky** [comment] 2019-01-27 02:15
I had some time to study this gist today:

```
	"github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	"github.com/stripe/skycfg"
	yaml "gopkg.in/yaml.v2"

	gogo_proto "github.com/gogo/protobuf/proto"
...
func (*protoRegistry) UnstableProtoMessageType(name string) (reflect.Type, error) {
	if t := proto.MessageType(name); t != nil {
		return t, nil
	}
	if t := gogo_proto.MessageType(name); t != nil {
		return t, nil
	}
	return nil, nil
}
```

You're using the same package for both `golang/protobuf` and `gogo/protobuf` registries.

You can also checkout the example I have here:  https://github.com/dilyevsky/skycfg/blob/reproduce/duration-conv/_examples/reproduce/main.go
